let y = 0
let x = 0
basic.showLeds(`
    . . . . .
    . # # # .
    . # # # .
    . # # # .
    . . . . .
    `)
basic.forever(function () {
    if (input.buttonIsPressed(Button.A)) {
        // partie 1 de la musique
        for (let index = 0; index < 2; index++) {
            music.playTone(494, music.beat(BeatFraction.Quarter))
            music.playTone(392, music.beat(BeatFraction.Quarter))
            music.playTone(330, music.beat(BeatFraction.Quarter))
            music.playTone(466, music.beat(BeatFraction.Quarter))
            music.playTone(392, music.beat(BeatFraction.Quarter))
            music.playTone(330, music.beat(BeatFraction.Quarter))
            music.playTone(466, music.beat(BeatFraction.Quarter))
            music.playTone(392, music.beat(BeatFraction.Quarter))
            music.playTone(494, music.beat(BeatFraction.Quarter))
            music.playTone(392, music.beat(BeatFraction.Quarter))
            music.playTone(330, music.beat(BeatFraction.Quarter))
            music.playTone(466, music.beat(BeatFraction.Quarter))
            music.playTone(392, music.beat(BeatFraction.Quarter))
            music.playTone(330, music.beat(BeatFraction.Quarter))
            music.playTone(523, music.beat(BeatFraction.Quarter))
            music.playTone(466, music.beat(BeatFraction.Eighth))
            music.playTone(494, music.beat(BeatFraction.Quarter))
            music.playTone(392, music.beat(BeatFraction.Quarter))
            music.playTone(330, music.beat(BeatFraction.Quarter))
            music.playTone(466, music.beat(BeatFraction.Eighth))
            music.playTone(392, music.beat(BeatFraction.Quarter))
            music.playTone(330, music.beat(BeatFraction.Quarter))
            music.playTone(466, music.beat(BeatFraction.Eighth))
            music.playTone(392, music.beat(BeatFraction.Quarter))
            music.playTone(494, music.beat(BeatFraction.Quarter))
            music.playTone(392, music.beat(BeatFraction.Quarter))
            music.playTone(330, music.beat(BeatFraction.Quarter))
            music.playTone(294, music.beat(BeatFraction.Whole))
            basic.pause(100)
        }
        basic.pause(200)
        // 2e partie de la musique
        for (let index = 0; index < 2; index++) {
            music.playTone(659, music.beat(BeatFraction.Whole))
            music.playTone(494, music.beat(BeatFraction.Whole))
            basic.pause(200)
            music.playTone(622, music.beat(BeatFraction.Whole))
            music.playTone(494, music.beat(BeatFraction.Whole))
            basic.pause(50)
            music.playTone(587, music.beat(BeatFraction.Whole))
            music.playTone(659, music.beat(BeatFraction.Half))
            music.playTone(587, music.beat(BeatFraction.Half))
            music.playTone(554, music.beat(BeatFraction.Whole))
            music.playTone(494, music.beat(BeatFraction.Half))
            music.playTone(440, music.beat(BeatFraction.Half))
            basic.pause(50)
            music.playTone(440, music.beat(BeatFraction.Quarter))
            music.playTone(494, music.beat(BeatFraction.Quarter))
            music.playTone(523, music.beat(BeatFraction.Half))
            music.playTone(587, music.beat(BeatFraction.Quarter))
            music.playTone(622, music.beat(BeatFraction.Quarter))
            music.playTone(659, music.beat(BeatFraction.Quarter))
            music.playTone(494, music.beat(BeatFraction.Quarter))
            music.playTone(392, music.beat(BeatFraction.Quarter))
            music.playTone(440, music.beat(BeatFraction.Quarter))
            music.playTone(494, music.beat(BeatFraction.Quarter))
            music.playTone(523, music.beat(BeatFraction.Quarter))
            music.playTone(494, music.beat(BeatFraction.Half))
            music.playTone(440, music.beat(BeatFraction.Half))
            music.playTone(392, music.beat(BeatFraction.Half))
            music.playTone(349, music.beat(BeatFraction.Half))
            basic.pause(50)
            music.playTone(392, music.beat(BeatFraction.Half))
            music.playTone(415, music.beat(BeatFraction.Eighth))
            music.playTone(440, music.beat(BeatFraction.Half))
            music.playTone(523, music.beat(BeatFraction.Half))
            music.playTone(440, music.beat(BeatFraction.Half))
            music.playTone(494, music.beat(BeatFraction.Whole))
            basic.pause(100)
        }
        basic.pause(100)
    } else {
        if (input.buttonIsPressed(Button.B)) {
            music.playTone(370, music.beat(BeatFraction.Quarter))
            music.playTone(466, music.beat(BeatFraction.Quarter))
            basic.pause(100)
            music.playTone(370, music.beat(BeatFraction.Quarter))
            music.playTone(311, music.beat(BeatFraction.Half))
            music.playTone(415, music.beat(BeatFraction.Quarter))
            music.playTone(349, music.beat(BeatFraction.Quarter))
            basic.pause(100)
            music.playTone(277, music.beat(BeatFraction.Quarter))
            music.playTone(311, music.beat(BeatFraction.Quarter))
            basic.pause(100)
            music.playTone(311, music.beat(BeatFraction.Half))
            basic.pause(150)
            music.playTone(370, music.beat(BeatFraction.Double))
            basic.pause(200)
            music.playTone(311, music.beat(BeatFraction.Quarter))
            basic.pause(100)
            music.playTone(370, music.beat(BeatFraction.Quarter))
            music.playTone(415, music.beat(BeatFraction.Quarter))
            basic.pause(100)
            music.playTone(466, music.beat(BeatFraction.Quarter))
            basic.pause(100)
            music.playTone(622, music.beat(BeatFraction.Whole))
            basic.pause(100)
            music.playTone(554, music.beat(BeatFraction.Half))
            basic.pause(100)
            music.playTone(494, music.beat(BeatFraction.Half))
            music.playTone(466, music.beat(BeatFraction.Half))
            basic.pause(50)
            music.playTone(554, music.beat(BeatFraction.Half))
            music.playTone(494, music.beat(BeatFraction.Half))
            music.playTone(466, music.beat(BeatFraction.Half))
            basic.pause(100)
            music.playTone(622, music.beat(BeatFraction.Half))
            music.playTone(554, music.beat(BeatFraction.Half))
            music.playTone(466, music.beat(BeatFraction.Whole))
            basic.pause(200)
            music.playTone(370, music.beat(BeatFraction.Half))
            basic.pause(200)
            music.playTone(370, music.beat(BeatFraction.Quarter))
            basic.pause(100)
            music.playTone(494, music.beat(BeatFraction.Half))
            music.playTone(466, music.beat(BeatFraction.Half))
            basic.pause(50)
            music.playTone(554, music.beat(BeatFraction.Half))
            music.playTone(494, music.beat(BeatFraction.Half))
            music.playTone(466, music.beat(BeatFraction.Half))
            basic.pause(100)
            music.playTone(622, music.beat(BeatFraction.Half))
            music.playTone(554, music.beat(BeatFraction.Half))
            music.playTone(466, music.beat(BeatFraction.Whole))
            basic.pause(100)
            music.playTone(370, music.beat(BeatFraction.Half))
            basic.pause(200)
            music.playTone(370, music.beat(BeatFraction.Whole))
        }
    }
})
basic.forever(function () {
    for (let index = 0; index < 5; index++) {
        for (let index = 0; index < 5; index++) {
            led.toggle(x, y)
            basic.pause(50)
            x += 1
        }
        basic.pause(50)
        x = 0
        y += 1
    }
    y = 0
})
